# Generated by Django 4.1.5 on 2023-10-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descript_text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
