# Generated by Django 4.1.5 on 2023-10-26 10:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_descript_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descript_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
