# Generated by Django 4.2.7 on 2023-12-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_brend_product_brend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brend',
            new_name='Productclass',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brend',
            new_name='productclass',
        ),
    ]
