# Generated by Django 4.2.7 on 2024-01-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_topproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlyOneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='./images')),
                ('productclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productclass')),
            ],
        ),
    ]
